[theme]
# El botón de accionar y detalles importantes
primaryColor = "#3b82f6" 

# Fondo general de la app (Celeste clarito)
backgroundColor = "#ffffff"

# Fondo del menú lateral (Gris/Blanco para que haga contraste suave)
secondaryBackgroundColor = "#f8fafc" 

# Texto oscuro para modo claro
textColor = "#0f172a" 

font = "sans serif"
base = "light"